version: "3.7"
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: /docker/entrypoint.sh
    volumes:
      - ./app:/app
      - ./docker:/docker
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
  webserver:
    image: nginx:1.19.8
    container_name: webserver
    ports:
      - 8000:80
    depends_on:
      - "php"
    volumes:
      - ./app:/app
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf

